# This will be removed when this project has more than one maintainers

name: auto-approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  auto_approve:
    if: |
      github.event.pull_request.user.login == 'kanarus' &&
      !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - run: gh pr review ${{ github.event.number }} --approve --body "auto-approve by bot"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
