name: CI

on:
  pull_request:
  push:
    branches: [main, v*]

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: ['stable', 'nightly']

    steps:
      - uses: actions/checkout@v4

      - name: Setup mold
        run:  |
          sudo apt install mold clang
          echo '[target.x86_64-unknown-linux-gnu]'                     >> $HOME/.cargo/config.toml
          echo 'linker    = "clang"'                                   >> $HOME/.cargo/config.toml
          echo 'rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]' >> $HOME/.cargo/config.toml

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Check buildability
        run: cargo check

      - name: Test availability at anywhere
        run: |
          cargo install --path .
          cargo new test
          cd test
          echo ''                         >> Cargo.toml
          echo '[package.metadata.tasks]' >> Cargo.toml
          echo 'greet = "echo hello"'     >> Cargo.toml
          cargo task greet | grep 'hello'
