name: CI

on:
  pull_request:
  push:
    branches: [main, v*]

jobs:
  CI:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable, nightly]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Check buildability
        run: cargo check

      - name: Test availability at anywhere
        shell: bash
        run: |
          cargo install --path .
          cargo new sample
          cd sample
          echo ''                         >> Cargo.toml
          echo '[package.metadata.tasks]' >> Cargo.toml
          echo 'greet = "echo hello"'     >> Cargo.toml
          cargo task greet
          cargo task greet | grep 'hello'
